name: CI

on:
  workflow_dispatch:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install the dependencies using the package manager whose lock file is in the root dir
        uses: jaid/action-npm-install@v1.2.1
      - name: Lint, build and test
        run: npm run prepack
